### PR TITLE
Move `pigz` to done in arch migrators

### LINKED ISSUE #1888: `pigz` shown in migrator errors, but is already done
Seeing `pigz` in the bot errors for the arch migrator and macOS ARM.

<details>
<summary>arch migrator</summary>

Screenshot 2023-10-12 at 1 49 30 PM

</details>

<details>
<summary>macOS ARM migrator</summary>

Screenshot 2023-10-12 at 1 49 55 PM

</details>

However arch migration already happened in PR ( https://github.com/conda-forge/pigz-feedstock/pull/18 ) and macOS ARM migration happened in PR ( https://github.com/conda-forge/pigz-feedstock/pull/20 )

Is there a way to clear the error status on these?

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/regro/cf-scripts/issues/1888

### CODE REVIEW

**Comment by beckermr** [comment]
Remember you have to edit the pr info files like last time.

**Comment by beckermr** [comment]
Remember you have to edit the pr info files.

**Comment by jakirkham** [comment]
Sorry Matt. I'm not following. Should there be PRs tracked if the bot errored?

**Comment by beckermr** [comment]
No but the pre pr migration errors are in those files.

**Comment by jakirkham** [comment]
Ok here are the files I see, which of these should we update?

```
$ git grep -l 'pigz'
all_feedstocks.json
graph.json
node_attrs/6/6/3/3/3/xopen.json
node_attrs/b/a/3/f/f/makeself.json
node_attrs/d/2/5/f/0/pigz.json
ranked_hubs_authorities.json
status/migration_json/aarch64andppc64leaddition.json
status/migration_json/armosxaddition.json
status/migration_svg/aarch64andppc64leaddition.svg
status/migration_svg/armosxaddition.svg
```

**Comment by beckermr** [comment]
That grep doesn't search the file names, only their contents. Look for the file names with the package name and you'll find the right spot.

**Comment by jakirkham** [comment]
Ah ok! That makes more sense 😅 Thanks Matt! 🙏

Now I see

```
$ git ls-files '*pigz*'
node_attrs/d/2/5/f/0/pigz.json
pr_info/d/2/5/f/0/pigz.json
version_pr_info/d/2/5/f/0/pigz.json
versions/d/2/5/f/0/pigz.json
```

Take it we want `pr_info/d/2/5/f/0/pigz.json`, right? Or am I still missing something?

**Comment by jakirkham** [comment]
How does that look?

Also the `pr_json/*` blobs referenced appear to already be removed. Guessing that is ok? Or do we need to recover those and modify them somehow?

**Comment by beckermr** [comment]
Look down at the bottom for the pre pr migrator status. Clear that for aarch too.

**Comment by jakirkham** [comment]
Meaning this? It appears empty. Or should the line be deleted altogether?

```
$ git grep 'pre_pr_migrator_status' -- pr_info/d/2/5/f/0/pigz.json
pr_info/d/2/5/f/0/pigz.json: "pre_pr_migrator_status": {},
```

**Comment by beckermr** [comment]
Ohhh weird. Let's merge and see what happens.

**Comment by jakirkham** [comment]
Sounds good. Thanks again Matt! 🙏

Happy to follow up as needed 🙂

**Comment by jakirkham** [comment]
Looks like the bot added `pigz` to awaiting PRs for both migrators in commit: https://github.com/regro/cf-graph-countyfair/commit/819cc3f30dc26d6922f5bf03d80a3f5ce51d7145

That's a good start. Let's see if it figures out that both are done already

**Pull request merged**
