### PR TITLE
Reset version PR info of datatoolbox

### PR DESCRIPTION
**Pull request by coroa**
Last year we wrongly released a version `5.0` of the datatoolbox package to first pypi and then conda-forge, while we had only intended to bump it up to `0.5.0`.

After removing this version from pypi, we had it marked as broken through: https://github.com/conda-forge/admin-requests/pull/522 .

But ever since then, new pypi releases did not lead to update PRs by the regro-cf-bot, therefore, I think, we need to reset the version PR here.

### CODE REVIEW

**Comment by coroa** [comment]
@beckermr @jakirkham @pavelzw could you approve or suggest a better to do this?

**Comment by pavelzw** [comment]
Take a look at https://github.com/conda-forge/typst-feedstock/pull/5/files. If you add `5.0` to the excluded version updates in the feedstock, this should also fix it.

**Comment by beckermr** [comment]
Either method should work AFAIK. The bot is a one-way ratchet on versions.

**Comment by coroa** [comment]
Thanks a lot both :)

**Pull request merged**
