### PR TITLE
Fix incorrect migration error for CuPy + PY312

### PR DESCRIPTION
**Pull request by leofang**
xref:
- https://github.com/conda-forge/cupy-feedstock/issues/234#issuecomment-1883929252
- https://github.com/conda-forge/cupy-feedstock/pull/235

@beckermr am I doing the right thing? I am clueless...

cc: @jakirkham

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Leo! 🙏

Found a better example than the one I shared previously: https://github.com/regro/cf-graph-countyfair/pull/10

**Comment by beckermr** [comment]
Assuming the bot never issued a pr, this fix should work.

**Comment by jakirkham** [comment]
Ok cool

Yeah [not seeing one]( https://github.com/conda-forge/cupy-feedstock/pulls?q=is%3Apr+author%3Aregro-cf-autotick-bot+python312 )

**Comment by leofang** [comment]
Thanks, guys! It seems we kicked it out of the "not-solvable" tab
截圖 2024-01-10 下午11 46 22
Let's see if the bot can move it to done...

**Comment by leofang** [comment]
Unfortunately it's not fixed, @beckermr any other idea that we can try?

btw @jakirkham the not-solvable error only happens in the CUDA 11.8 flavor, not 12.0, does it ring any bell? e.g.
```
linux_64_c_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11python3.10.____cpython: Could not solve for environment specs
The following package could not be installed
└─ cusparselt 0.2.0.1.* 1 does not exist (perhaps a typo or a missing channel).
```

**Comment by beckermr** [comment]
Yeah the bot will try to add the migrator and rerender. If the feedstock changes, it will then check if things are solvable. This must be what happened here.

**Comment by leofang** [comment]
But we've migrated, so the feedstock should not change at all, right?

**Comment by beckermr** [comment]
Apparently not? Sometimes a smithy release will cause unrelated changes. The bot isn't smart enough to figure that out.

**Comment by leofang** [comment]
@beckermr apparently you're right... https://github.com/conda-forge/cupy-feedstock/pull/236 Let's merge it and see if the bot would behave? Any extra step that I should take?

**Comment by beckermr** [comment]
yes we should try that. thanks for checking!

**Comment by jakirkham** [comment]
Does the bot recheck on its own now that we have re-rendered the feedstock or do we need to reset the CuPy Python 3.12 migration test?

**Comment by beckermr** [comment]
It will recheck on its own eventually.

**Comment by jakirkham** [comment]
Looks like it did and had [the same issue]( https://github.com/regro/cf-scripts/actions/runs/7490511551/job/20389551684#step:8:4201 )

**Comment by leofang** [comment]
Interestingly, I can reproduce the error by using the exact requirement as the bot did:
```
$ mamba create -n bbbbb cupy cusparselt="0.2.0.1.* 1" cuda-version=11.8

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['cupy', 'cusparselt=0.2.0.1[build=1]', 'cuda-version=11.8']

warning  libmamba Cache file "/home/leof/miniforge3/pkgs/cache/497deca9.json" was modified by another program
warning  libmamba Cache file "/home/leof/miniforge3/pkgs/cache/09cdf8bf.json" was modified by another program
conda-forge/noarch                                  15.3MB @   8.2MB/s  2.2s
conda-forge/linux-64                                37.3MB @   7.8MB/s  5.9s
Could not solve for environment specs
The following package could not be installed
└─ cusparselt 0.2.0.1* 1 does not exist (perhaps a typo or a missing channel).
```
Do we know why the build number 1 has to be added there? If I remove it the env can be created just fine.

**Comment by beckermr** [comment]
So it is a solver bug. That's fun!

**Comment by jakirkham** [comment]
Maybe this is relevant ( https://github.com/conda-forge/cupy-feedstock/pull/238 )?

**Comment by beckermr** [comment]
Could be! Sorry for the trouble and thanks for working this. The bot is pretty strict about this things and it is hard to find ways to loosen the restrictions and keep things working at the same time.

**Comment by jakirkham** [comment]
Unfortunately we still see [the same error]( https://github.com/regro/cf-scripts/actions/runs/7496264925/job/20407978483#step:8:9889 )

**Comment by jakirkham** [comment]
Going to try expressing this requirement in a different way ( https://github.com/conda-forge/cupy-feedstock/pull/240 )

If this still doesn't work, is there a good way to get insight on how the bot is constructing this constraint on `cusparselt`? That might help us come up with better options

**Comment by beckermr** [comment]
Yep I'd add a test to the solver repo and figure out why it is not passing.

**Comment by jakirkham** [comment]
Am still seeing [an error]( https://github.com/regro/cf-scripts/actions/runs/7502208531/job/20424400660#step:8:21570 ) after the recent change

Though it is weird as the bot shows the dependencies like so

```
  ['numpy >=1.21,<2',
   'nccl >=2.19.4.1,<3.0a0',
   'cudatoolkit',
   'cutensor >=1.7.0.1,<2.0a0',
   'cudnn >=8.8.0.121,<9.0a0',
   'python_abi 3.10.* *_cp310',
   'libstdcxx-ng >=12',
   'python >=3.10,<3.11.0a0',
   'libgcc-ng >=12',
   'cusparselt 0.2.0.1.* 1',
   'fastrlock',
   'cuda-version >=11.2,<12',
   '__glibc >=2.17,<3.0.a0']
```

Though [the `cusparselt` dependency]( https://github.com/conda-forge-admin/cupy-feedstock/blob/9fcc17512bd45373afaa6fabdad7bd03941daa17/recipe/meta.yaml#L137 ) is expressed like this

```yaml
    - cusparselt ~=0.2.0.0
```

Am wondering if the bot has some stale metadata somewhere that it is pulling from. Are the recipes cached somewhere? If so, can we purge that cache somehow?

**Pull request merged**
