### PR TITLE
Fix new_version in onnx

### PR DESCRIPTION
**Pull request by JanJaguschQC**
There was a typo in a recent `onnx` release: It was tagged as `12.0.0` (probably, instead of `1.12.0`).

Since then, the autotick bot hasn't been able to open pull requests for new `onnx` versions, because the semantic version `12.0.0` was greater than, for example, `1.14.0`.

This PR resets the `new_version` in the `onnx` metadata to the latest release on Conda-Forge: `1.11.0`. This should enable automatic version updates again.

https://pypi.org/project/onnx/#history

### CODE REVIEW

**Comment by JanJaguschQC** [comment]
@beckermr, could you please take a look at this? Thanks!

**Comment by beckermr** [comment]
you need to add this to the list of ignored version on the feedstock - see here: https://github.com/conda-forge/pixmappy-feedstock/blob/main/conda-forge.yml#L5

**Comment by JanJaguschQC** [comment]
> you need to add this to the list of ignored version on the feedstock - see here: https://github.com/conda-forge/pixmappy-feedstock/blob/main/conda-forge.yml#L5

Thanks for your fast reply, @beckermr. I followed your suggestion in https://github.com/conda-forge/onnx-feedstock/pull/93 but it still doesn't seem to work. There is still no version PR in the feedstock and the metadata in the graph hasn't been updated: https://github.com/regro/cf-graph-countyfair/blob/master/version_pr_info/9/1/d/4/c/onnx.json.

Maybe your approach only works when the `new_version` field in the metadata isn't tainted yet?

In this PR I was copying what was done in https://github.com/regro/cf-graph-countyfair/pull/1.

**Comment by beckermr** [comment]
wait a day or so for the bot to catchup

**Comment by JanJaguschQC** [comment]
Still no update in the feedstock, @beckermr. Can you take another look, please?

**Comment by beckermr** [comment]
Thank you for your patience! I think this may be a bug. Let's see if this PR fixes it: https://github.com/regro/cf-scripts/pull/1679

**Comment by JanJaguschQC** [comment]
Thanks @beckermr! It's a bit hard for me to test [because someone added the new ONNX version manually](https://github.com/conda-forge/onnx-feedstock/pull/94#issuecomment-1548576193), but it seems like your fix worked:

image


https://github.com/regro/cf-graph-countyfair/commit/03012935a7e7cbcc0fb4419fe46ca77c76c3b6e5#diff-91b3332931c45e82f9ca9d42e87e9ea23d62f715560b24c7d64d8bf568cacc0c

**Pull request closed without merging**
